//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Localization.Strings_Fr", typeof(Strings_Fr).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des promotions.
        /// </summary>
        public static string CardViewModel_Progress {
            get {
                return ResourceManager.GetString("CardViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la Date.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChangeDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChangeDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez vos photos supplémentaires! (optionnel).
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChooseAdditionalPicMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChooseAdditionalPicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez votre photo de couverture!.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChoosePicMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChoosePicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_CreatePromoBtn {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.CreatePromoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de la promotion:.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_EndDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.EndDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ErrorMissingField {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ErrorMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion en cours....
        /// </summary>
        public static string CreatePromotionPart2ViewModel_Progress {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début de la promotion: .
        /// </summary>
        public static string CreatePromotionPart2ViewModel_StartDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.StartDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vêtements.
        /// </summary>
        public static string CreatePromotionViewModel_ApparelRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ApparelRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string CreatePromotionViewModel_CategoriesMsg {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.CategoriesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string CreatePromotionViewModel_ContinueBtn {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreatePromotionViewModel_DescriptionHint {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.DescriptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Électronique.
        /// </summary>
        public static string CreatePromotionViewModel_ElectronicsRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ElectronicsRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant.
        /// </summary>
        public static string CreatePromotionViewModel_ErrorMissingField {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ErrorMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaussure.
        /// </summary>
        public static string CreatePromotionViewModel_FootwearRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.FootwearRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijoux.
        /// </summary>
        public static string CreatePromotionViewModel_JewelleryRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.JewelleryRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string CreatePromotionViewModel_RestaurantsRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.RestaurantsRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string CreatePromotionViewModel_ServicesRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ServicesRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string CreatePromotionViewModel_TitleHint {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.TitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes offres aimées.
        /// </summary>
        public static string LikedPromotionsViewModel_LikedDeals {
            get {
                return ResourceManager.GetString("LikedPromotionsViewModel.LikedDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la carte.
        /// </summary>
        public static string LikedPromotionsViewModel_SeeMap {
            get {
                return ResourceManager.GetString("LikedPromotionsViewModel.SeeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos du contenu.
        /// </summary>
        public static string LoginSettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la langue de l&apos;application.
        /// </summary>
        public static string LoginSettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCHAND.
        /// </summary>
        public static string LoginViewModel_MerchantLabel {
            get {
                return ResourceManager.GetString("LoginViewModel.MerchantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de compte?.
        /// </summary>
        public static string LoginViewModel_NoAccountMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.NoAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        public static string LoginViewModel_OrMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.OrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Connecter.
        /// </summary>
        public static string LoginViewModel_SignInButton {
            get {
                return ResourceManager.GetString("LoginViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faites un Apeçu.
        /// </summary>
        public static string LoginViewModel_TakeAGlimpse {
            get {
                return ResourceManager.GetString("LoginViewModel.TakeAGlimpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string LoginViewModel_VendorSignUpButton {
            get {
                return ResourceManager.GetString("LoginViewModel.VendorSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue à Glimpse.
        /// </summary>
        public static string LoginViewModel_WelcomeMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez ci-dessous pour decouvrir les offres à proximité!.
        /// </summary>
        public static string LoginViewModel_WelcomeMsgInstructions {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsgInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string MenuViewModel_Logout {
            get {
                return ResourceManager.GetString("MenuViewModel.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string MenuViewModel_Profile {
            get {
                return ResourceManager.GetString("MenuViewModel.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string MenuViewModel_Promotions {
            get {
                return ResourceManager.GetString("MenuViewModel.Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string MenuViewModel_Settings {
            get {
                return ResourceManager.GetString("MenuViewModel.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de cette offre.
        /// </summary>
        public static string PromoDetailsViewModel_AboutThisDeal {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.AboutThisDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Acheté.
        /// </summary>
        public static string PromoDetailsViewModel_Bought {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des images.
        /// </summary>
        public static string PromoDetailsViewModel_Progress {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos du contenu.
        /// </summary>
        public static string SettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la langue de l&apos;application.
        /// </summary>
        public static string SettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string SignInViewModel_EmailHint {
            get {
                return ResourceManager.GetString("SignInViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string SignInViewModel_ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou mot de passe incorrect..
        /// </summary>
        public static string SignInViewModel_IncorrectInputMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.IncorrectInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant..
        /// </summary>
        public static string SignInViewModel_MissingField {
            get {
                return ResourceManager.GetString("SignInViewModel.MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de Passe.
        /// </summary>
        public static string SignInViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("SignInViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification ....
        /// </summary>
        public static string SignInViewModel_Progress {
            get {
                return ResourceManager.GetString("SignInViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SignInViewModel_SignInButton {
            get {
                return ResourceManager.GetString("SignInViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes promotions.
        /// </summary>
        public static string VendorProfilePageViewModel_MyPromotions {
            get {
                return ResourceManager.GetString("VendorProfilePageViewModel.MyPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone de l&apos;entreprise.
        /// </summary>
        public static string VendorSignUpViewModel_BusinessPhoneNumberHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.BusinessPhoneNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie.
        /// </summary>
        public static string VendorSignUpViewModel_CompanyHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.CompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez le mot de passe.
        /// </summary>
        public static string VendorSignUpViewModel_ConfirmPasswordHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ConfirmPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string VendorSignUpViewModel_EmailHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est déjà utilisé.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailExistsMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;email n&apos;est pas valide.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailIsNotValidMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailIsNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorMissingFieldMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorMissingFieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passe ne correspondent pas.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorPasswordMatchMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorPasswordMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un lieu.
        /// </summary>
        public static string VendorSignUpViewModel_LocationButton {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.LocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de Passe.
        /// </summary>
        public static string VendorSignUpViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription en cours ....
        /// </summary>
        public static string VendorSignUpViewModel_Progress {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string VendorSignUpViewModel_SignUp {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.SignUp", resourceCulture);
            }
        }
    }
}
