//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Promotions.
        /// </summary>
        public static string CardViewModel_Progress {
            get {
                return ResourceManager.GetString("CardViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Date.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChangeDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChangeDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your additional pictures! (optional).
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChooseAdditionalPicMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChooseAdditionalPicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your cover picture!.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ChoosePicMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ChoosePicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_CreatePromoBtn {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.CreatePromoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion End Date: .
        /// </summary>
        public static string CreatePromotionPart2ViewModel_EndDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.EndDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Required Field.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_ErrorMissingField {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.ErrorMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Promotion....
        /// </summary>
        public static string CreatePromotionPart2ViewModel_Progress {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Start Date:.
        /// </summary>
        public static string CreatePromotionPart2ViewModel_StartDateMsg {
            get {
                return ResourceManager.GetString("CreatePromotionPart2ViewModel.StartDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        public static string CreatePromotionViewModel_ApparelRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ApparelRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CreatePromotionViewModel_CategoriesMsg {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.CategoriesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string CreatePromotionViewModel_ContinueBtn {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreatePromotionViewModel_DescriptionHint {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.DescriptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string CreatePromotionViewModel_ElectronicsRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ElectronicsRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Required Field.
        /// </summary>
        public static string CreatePromotionViewModel_ErrorMissingField {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ErrorMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwear.
        /// </summary>
        public static string CreatePromotionViewModel_FootwearRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.FootwearRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewellery.
        /// </summary>
        public static string CreatePromotionViewModel_JewelleryRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.JewelleryRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string CreatePromotionViewModel_RestaurantsRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.RestaurantsRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string CreatePromotionViewModel_ServicesRadio {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.ServicesRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CreatePromotionViewModel_TitleHint {
            get {
                return ResourceManager.GetString("CreatePromotionViewModel.TitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Liked Deals.
        /// </summary>
        public static string LikedPromotionsViewModel_LikedDeals {
            get {
                return ResourceManager.GetString("LikedPromotionsViewModel.LikedDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Map.
        /// </summary>
        public static string LikedPromotionsViewModel_SeeMap {
            get {
                return ResourceManager.GetString("LikedPromotionsViewModel.SeeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Content.
        /// </summary>
        public static string LoginSettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the app.
        /// </summary>
        public static string LoginSettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERCHANTS.
        /// </summary>
        public static string LoginViewModel_MerchantLabel {
            get {
                return ResourceManager.GetString("LoginViewModel.MerchantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string LoginViewModel_NoAccountMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.NoAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LoginViewModel_OrMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.OrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginViewModel_SignInButton {
            get {
                return ResourceManager.GetString("LoginViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take A Glimpse.
        /// </summary>
        public static string LoginViewModel_TakeAGlimpse {
            get {
                return ResourceManager.GetString("LoginViewModel.TakeAGlimpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LoginViewModel_VendorSignUpButton {
            get {
                return ResourceManager.GetString("LoginViewModel.VendorSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Glimpse.
        /// </summary>
        public static string LoginViewModel_WelcomeMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap below to Glimpse Nearby Deals!.
        /// </summary>
        public static string LoginViewModel_WelcomeMsgInstructions {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsgInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuViewModel_Logout {
            get {
                return ResourceManager.GetString("MenuViewModel.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuViewModel_Profile {
            get {
                return ResourceManager.GetString("MenuViewModel.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string MenuViewModel_Promotions {
            get {
                return ResourceManager.GetString("MenuViewModel.Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuViewModel_Settings {
            get {
                return ResourceManager.GetString("MenuViewModel.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this deal.
        /// </summary>
        public static string PromoDetailsViewModel_AboutThisDeal {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.AboutThisDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Bought.
        /// </summary>
        public static string PromoDetailsViewModel_Bought {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Images.
        /// </summary>
        public static string PromoDetailsViewModel_Progress {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Content.
        /// </summary>
        public static string SettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the app.
        /// </summary>
        public static string SettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string SignInViewModel_EmailHint {
            get {
                return ResourceManager.GetString("SignInViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string SignInViewModel_ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string SignInViewModel_IncorrectInputMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.IncorrectInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required field..
        /// </summary>
        public static string SignInViewModel_MissingField {
            get {
                return ResourceManager.GetString("SignInViewModel.MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignInViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("SignInViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string SignInViewModel_Progress {
            get {
                return ResourceManager.GetString("SignInViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInViewModel_SignInButton {
            get {
                return ResourceManager.GetString("SignInViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Promotions.
        /// </summary>
        public static string VendorProfilePageViewModel_MyPromotions {
            get {
                return ResourceManager.GetString("VendorProfilePageViewModel.MyPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Phone Number.
        /// </summary>
        public static string VendorSignUpViewModel_BusinessPhoneNumberHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.BusinessPhoneNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string VendorSignUpViewModel_CompanyHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.CompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string VendorSignUpViewModel_ConfirmPasswordHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ConfirmPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string VendorSignUpViewModel_EmailHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already being used.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailExistsMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailIsNotValidMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailIsNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required field.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorMissingFieldMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorMissingFieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorPasswordMatchMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorPasswordMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Location.
        /// </summary>
        public static string VendorSignUpViewModel_LocationButton {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.LocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string VendorSignUpViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up in progress....
        /// </summary>
        public static string VendorSignUpViewModel_Progress {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string VendorSignUpViewModel_SignUp {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.SignUp", resourceCulture);
            }
        }
    }
}
